name: Deploy egop runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  
#  prepare-environment:
#    runs-on: self-hosted
#    steps:
#      - name: Stop and remove containers, networks
#        run: docker compose down
#      - name: Remove unused data
#        run: docker system prune -a -f
        
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose
        run: docker compose -f docker-compose.yml up --build --detach